### ISSUE TITLE
"Using webpack" section of "getting started" not clear

### ISSUE THREAD

**Issue by slaweet** [mswjs/mswjs.io#54]
I was trying to follow this part of the guide
https://github.com/mswjs/mswjs.io/blob/5b607af55f59992f624da158c001cb5f2fc14913/docs/getting-started/integrate/browser.mdx#L87-L105 https://mswjs.io/docs/getting-started/integrate/browser#using-webpack

And it's not clear if this should be done in addition or instead of the previous step (Using conditional import). Because with each of the options I have some issue:

- If "Using webpack" section is **instead of**, "Using conditional import", then I don't understand how/where to call an equivalent of `worker.start()`
- If it's **in addition**, then I wonder if it could be achieved just with `webpackChunkName`:
```js
if (process.env.NODE_ENV === 'development') {                                                         
  import(/* webpackChunkName: "api-mock" */ '@/api/mocks/browser')                                    
    .then(({ worker }) => worker.start());                                                            
}  
```

I'm not too experienced with how webpack is supposed to work here, but I suppose I'm not the only one, so elaborating the docs could help also some other people out there.

**Comment by kettanaito** [comment]
Hey, @slaweet. Thanks for raising this.

Indeed, our webpack integration example is confusing. I believe it omits the `worker.start()` part, because it got copied from the old docs, where we used to recommend to call `worker.start()` as a part of `mocks/browser.js`. Since it's no longer a recommendation, when you read the webpack integration you raise a reasonable question regarding where the `worker.start()` should be called.

The intention is to use webpack integration **instead of** the conditional import one. Your example with an alias and a custom chunk name looks good. I'd think how to solve that on the webpack config's level alone.

I think that the webpack part of the browser integration make it overall confusing, and it should be moved to a standalone recipe for those who want that.

**Comment by kettanaito** [comment]
I've removed the webpack integration example from the [Browser integration page](https://mswjs.io/docs/getting-started/integrate/browser) to prevent confusion and also because it was an incomplete example to begin with. 

Such alternative integration scenario via webpack should be in the Recipes, and must include a webpack config that ensures the mock definition is imported, and the `worker.start()` is called. I don't have an official recommendation here, so I'm omitting this altogether for now.
